= Cache policy

ifdef::env-github[]
image:https://ci.gravitee.io/buildStatus/icon?job=gravitee-io/gravitee-policy-cache/master["Build status", link="https://ci.gravitee.io/job/gravitee-io/job/gravitee-policy-cache/"]
image:https://badges.gitter.im/Join Chat.svg["Gitter", link="https://gitter.im/gravitee-io/gravitee-io?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
endif::[]

== Phase

|===
|onRequest |onResponse

| X
|

|===

== Description

You can use the `cache` policy to cache upstream responses (content, status and headers) to eliminate the need for subsequent calls to
the back end.

This policy is based on a _cache resource_, which aligns the underlying cache system with the
API lifecycle (stop / start).

Consumers can bypass the cache by adding a `cache=BY_PASS_` query parameter or by providing a
`_X-Gravitee-Cache=BY_PASS_` HTTP header.

NOTE: If no cache resource is defined for the policy or it is not well configured, the API will not be deployed. The resource name is specified in the
policy configuration `cacheName`, as described below.

== Configuration

You can configure the policy with the following options:

|===
|Property |Required |Description |Type |Default

|cacheName|X|The cache resource used to store the element|string|
|key||The key used to store the element (support EL)|string|
|timeToLiveSeconds|X|Time to live of the element put in cache (Default to 10 minutes)|integer|600
|useResponseCacheHeaders||Time to live based on 'Cache-Control' and / or 'Expires' headers from backend response|boolean|false
|scope|X|Cached response can be set for a single consumer (application) or for all applications.<br><strong>WARNING:</strong> Please be aware that by using an \"API\" scope, data will be shared between all consumers !|API / APPLICATION|APPLICATION

|===

== Examples

The key used to store elements in cache can use the Gravitee Expression Language to provide a dynamic value.

TIP: To learn more about the Gravitee Expression Language, see the *API Publisher Guide*.

=== Key based on the `productId` query parameter

[source, json]
----
"key": "{#request.params['productId']}"
----

=== Key based on the `api-key` of the consumer

[source, json]
----
"key": "{#request.headers['X-Gravitee-Api-Key']}"
----

=== Key based on an API's property and a query parameter

[source, json]
----
"key": "{#properties['siteID']}-{#request.params['productId']}"
----

=== Configuration example

[source, json]
----
"cache": {
    "cacheName": "policy-cache",
    "key": "{#request.params['productId']}",
    "timeToLiveSeconds": 600,
    "useResponseCacheHeaders": false,
    "scope": "APPLICATION"
}
----
